### ISSUE TITLE
Link to CodePlayer.tv

### ISSUE THREAD

**Issue by mattpardee** [shvetsgroup/codeplayer#1]
In your readme you point to CodePlayer.tv as an easier way to create the JSON:

> Scenario is a JSON file with a list of actions. You could craft scenarios by hands, but that quickly becomes too tedious job for a non-trivial scenario. That's why I've created an editor, to streamline the scenarios production.

But this link doesn't appear to work (even if I go directly to CodePlayer.tv). Is there a location where the editor exists?

This tool is really cool! Thanks for building it!

**Comment by neochief** [comment]
The service does not exist yet, unfortunately.

**Comment by mattpardee** [comment]
OK, thanks for the prompt response!
